'use server';

/**
 * @fileOverview An AI agent that leverages multiple AI models (Grok, Gemini, GPT-4o) to generate responses,
 * compares and merges the results to reduce hallucinations, and rewrites the final response in the style of the selected AI agent.
 *
 * - multiAgentResponse - A function that handles the multi-agent response process.
 * - MultiAgentResponseInput - The input type for the multiAgentResponse function.
 * - MultiAgentResponseOutput - The return type for the multiAgentResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MultiAgentResponseInputSchema = z.object({
  prompt: z.string().describe('The user prompt to be processed by the AI agents.'),
  agentStyle: z.enum(['Friend', 'Teacher', 'Boss', 'Girlfriend', 'Religious Guide', 'Gym Coach', 'Comedian', 'Business Mentor']).describe('The desired style of the AI agent.'),
});
export type MultiAgentResponseInput = z.infer<typeof MultiAgentResponseInputSchema>;

const MultiAgentResponseOutputSchema = z.object({
  response: z.string().describe('The final response generated by the AI agent, incorporating the selected style.'),
});
export type MultiAgentResponseOutput = z.infer<typeof MultiAgentResponseOutputSchema>;

export async function multiAgentResponse(input: MultiAgentResponseInput): Promise<MultiAgentResponseOutput> {
  return multiAgentResponseFlow(input);
}

const multiAgentResponseFlow = ai.defineFlow(
  {
    name: 'multiAgentResponseFlow',
    inputSchema: MultiAgentResponseInputSchema,
    outputSchema: MultiAgentResponseOutputSchema,
  },
  async input => {
    // Simulate getting responses from multiple AI models (Grok, Gemini, GPT-4o)
    const grokResponsePromise = ai.generate({
      prompt: `Grok: ${input.prompt}`,
    });
    const geminiResponsePromise = ai.generate({
      prompt: `Gemini: ${input.prompt}`,
    });
    const gpt4oResponsePromise = ai.generate({
      prompt: `GPT-4o: ${input.prompt}`,
    });

    const [grokResponse, geminiResponse, gpt4oResponse] = await Promise.all([
      grokResponsePromise,
      geminiResponsePromise,
      gpt4oResponsePromise,
    ]);

    const grokText = grokResponse.text ?? '';
    const geminiText = geminiResponse.text ?? '';
    const gpt4oText = gpt4oResponse.text ?? '';

    // Dummy implementation for comparing and merging results to reduce hallucinations
    // In a real application, this would involve more sophisticated techniques
    const mergedResponse = `Grok: ${grokText}\nGemini: ${geminiText}\nGPT-4o: ${gpt4oText}`;

    // Rewrite the response in the style of the selected AI agent
    const agentRewritePrompt = ai.definePrompt({
      name: 'agentRewritePrompt',
      input: z.object({
        mergedResponse: z.string().describe('The merged response from multiple AI models.'),
        agentStyle: z.string().describe('The desired style of the AI agent (Friend, Teacher, Boss, etc.).'),
      }),
      output: z.object({
        rewrittenResponse: z.string().describe('The rewritten response in the style of the AI agent.'),
      }),
      prompt: `Rewrite the following response in the style of a {{agentStyle}}:\n\n{{{mergedResponse}}}`,      
    });

    const {output} = await agentRewritePrompt({
      mergedResponse: mergedResponse,
      agentStyle: input.agentStyle,
    });

    return {response: output!.rewrittenResponse!};
  }
);
